name: Build

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup bazel
        run: |
          # https://docs.bazel.build/versions/4.2.2/install-ubuntu.html
          sudo apt install curl gnupg
          curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg
          sudo mv bazel.gpg /etc/apt/trusted.gpg.d/
          echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
          sudo apt update && sudo apt install bazel

      - name: Install dependencies
        run: sudo apt install -y libopenblas-dev libomp-7-dev libstdc++6

      - name: Build faiss-server
        run: bazel build //:faiss-server
